app = "schede-clienti"
primary_region = "fra"

[build]
builtin = "node"

[http_service]
auto_start_machines = true
force_https = true
internal_port = 8080
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
