app = "schede-clienti"
primary_region = "fra"

[build]
builder = "paketobuildpacks/builder:base"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024